controller_manager:
    ros__parameters:
        update_rate: 300  # Hz
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster
        robot_joint_controller:
            type: robot_joint_controller/RobotJointControllerGroup
