# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

panda7/himloco:
  model_name: "panda7_model.pt"
  num_observations: 51
  observations: [ "ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100]
  clip_actions_upper: [100, 100, 100,
                       100, 100, 100,
                       100, 100, 100,
                       100, 100, 100]
  rl_kp: [150, 150, 150,
          150, 150, 150,
          150, 150, 150,
          150, 150, 150]
  rl_kd: [2, 2, 2,
          2, 2, 2,
          2, 2, 2,
          2, 2, 2]
  fixed_kp: [60, 60, 60,
             60, 60, 60,
             60, 60, 60,
             60, 60, 60]
  fixed_kd: [5, 5, 5,
             5, 5, 5,
             5, 5, 5,
             5, 5, 5]
  num_of_dofs: 12
  action_scale: [0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25, 
                1.00, 1.00, 1.00,
                1.00, 1.00, 1.00]
  torque_limits: [33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5]
  default_dof_pos: [ 0.000, 0.7580, -1.414,
                    0.000, 0.7580, -1.414,
                     0.000, 0.7580, -1.414,
                    0.000, 0.7580, -1.414,]
  joint_mapping: [0,1,2,3,4,5,6,7,8,9,10,11]
