lite3_gazebo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000

    # FL Controllers ---------------------------------------
    FL_HipX_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_HipX_joint

    FL_HipY_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_HipY_joint

    FL_Knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_Knee_joint

    # FR Controllers ---------------------------------------
    FR_HipX_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_HipX_joint

    FR_HipY_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_HipY_joint

    FR_Knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_Knee_joint

    # HL Controllers ---------------------------------------
    HL_HipX_controller:
        type: robot_joint_controller/RobotJointController
        joint: HL_HipX_joint

    HL_HipY_controller:
        type: robot_joint_controller/RobotJointController
        joint: HL_HipY_joint

    HL_Knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: HL_Knee_joint

    # HR Controllers ---------------------------------------
    HR_HipX_controller:
        type: robot_joint_controller/RobotJointController
        joint: HR_HipX_joint

    HR_HipY_controller:
        type: robot_joint_controller/RobotJointController
        joint: HR_HipY_joint

    HR_Knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: HR_Knee_joint

