g1_gazebo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000

    # Left Leg Controllers ---------------------------------------
    left_hip_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_hip_pitch_joint

    left_hip_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_hip_roll_joint

    left_hip_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_hip_yaw_joint

    left_knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_knee_joint

    left_ankle_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_ankle_pitch_joint

    left_ankle_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_ankle_roll_joint

    # Right Leg Controllers ---------------------------------------
    right_hip_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_hip_pitch_joint

    right_hip_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_hip_roll_joint

    right_hip_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_hip_yaw_joint

    right_knee_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_knee_joint

    right_ankle_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_ankle_pitch_joint

    right_ankle_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_ankle_roll_joint

    # Waist Controller ---------------------------------------
    waist_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: waist_yaw_joint

    waist_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: waist_roll_joint

    waist_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: waist_pitch_joint

    # Left Arm Controllers ---------------------------------------
    left_shoulder_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_shoulder_pitch_joint

    left_shoulder_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_shoulder_roll_joint

    left_shoulder_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_shoulder_yaw_joint

    left_elbow_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_elbow_joint

    left_wrist_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_wrist_roll_joint

    left_wrist_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_wrist_pitch_joint

    left_wrist_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: left_wrist_yaw_joint

    # Right Arm Controllers ---------------------------------------
    right_shoulder_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_shoulder_pitch_joint

    right_shoulder_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_shoulder_roll_joint

    right_shoulder_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_shoulder_yaw_joint

    right_elbow_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_elbow_joint

    right_wrist_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_wrist_roll_joint

    right_wrist_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_wrist_pitch_joint

    right_wrist_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: right_wrist_yaw_joint
