# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

panda3v2:
  dt: 0.005
  decimation: 4
  fixed_kp: [200, 200, 200,
             200, 200, 200,
             200, 200, 200,
             200, 200, 200]
  fixed_kd: [1, 1, 1,
             1, 1, 1,
             1, 1, 1,
             1, 1, 1]
  num_of_dofs: 12
  wheel_indices: []

  default_dof_pos: [0.000, 0.68, -1.3,
                    0.000, 0.68, -1.3,
                    0.000, 0.68, -1.3,
                    0.000, 0.68, -1.3]
  joint_names: ["FL_hip_joint", "FL_thigh_joint", "FL_calf_joint",
                "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint",
                "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint",
                "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint"]
  joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller"]
  # joint_names: ["FR_hip_joint", "FR_thigh_joint", "FR_calf_joint",
  #               "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint",
  #               "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint",
  #               "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint"]
  # joint_controller_names: ["FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
  #                          "FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
  #                          "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller",
  #                          "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

  damping_kd: [ 5, 6, 7,
                5, 6, 7,
                5, 6, 7,
                5, 6, 7]

  rosbag_save_path: "/home/yong/Desktop/仿真数据/04-14"
  rosbag_save_name: "47000"

  # joystick_type: ["beitong", "xbox", "sony", "onexplayer", "feizhi"] # xbox sony onexplayer beitong feizhi
  joystick_type: "xiaoji"

  algorithm: "himloco" # np3o himloco wmp

policies:
  RLFSMStateRLWalk:
    type: "himoloco_walk_ppo"
    selected: May28_17-29-10_6000
    policy_list:
      May25_16-13-47_4000:
        policy_config_path: "himoloco_walk_ppo/policy_May25_16-13-47_4000.yaml"
      May19_14-55-30_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May19_14-55-30_10000.yaml"
      May10_20-14-01_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May10_20-14-01_10000.yaml"
      May26_14-38-38_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May26_14-38-38_10000.yaml"
      May22_08-03-53_6600:
        policy_config_path: "himoloco_walk_ppo/policy_May22_08-03-53_6600.yaml"
      May26_11-28-35_4400:
        policy_config_path: "himoloco_walk_ppo/policy_May26_11-28-35_4400.yaml"
      May27_18-49-50_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May27_18-49-50_10000.yaml"
      May27_17-02-40_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May27_17-02-40_10000.yaml"
      May27_09-35-50_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May27_09-35-50_10000.yaml"
      May27_19-41-59_6000:
        policy_config_path: "himoloco_walk_ppo/policy_May27_19-41-59_6000.yaml"
      May27_09-47-32_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May27_09-47-32_10000.yaml"
      May28_11-46-43_2400:
        policy_config_path: "himoloco_walk_ppo/policy_May28_11-46-43_2400.yaml"
      May28_11-46-43_4400:
        policy_config_path: "himoloco_walk_ppo/policy_May28_11-46-43_4400.yaml"
      May28_10-21-51_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May28_10-21-51_10000.yaml"
      May28_17-29-10_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May28_17-29-10_10000.yaml"
      May28_17-30-41_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May28_17-30-41_10000.yaml"
      May28_07-46-09_10000:
        policy_config_path: "himoloco_walk_ppo/policy_May28_07-46-09_10000.yaml"
      May28_17-29-10_6000:
        policy_config_path: "himoloco_walk_ppo/policy_May28_17-29-10_6000.yaml"
      # May13_16-34-14_10000:
      #   policy_config_path: "himoloco_walk_ppo/policy_May13_16-34-14_10000.yaml"
      # May13_16-30-17_10000:
      #   policy_config_path: "himoloco_walk_ppo/policy_May13_16-30-17_10000.yaml"
      # May13_14-31-33_5400:
      #   policy_config_path: "himoloco_walk_ppo/policy_May13_14-31-33_5400.yaml"
      # May14_09-31-53_7000:
      #   policy_config_path: "himoloco_walk_ppo/policy_May14_09-31-53_7000.yaml"
      # May14_14-43-07_10000:
      #   policy_config_path: "himoloco_walk_ppo/policy_May14_14-43-07_10000.yaml"
      # May14_14-32-45_9200:
      #   policy_config_path: "himoloco_walk_ppo/policy_May14_14-32-45_9200.yaml"
      # May14_08-35-32_8800:
      #   policy_config_path: "himoloco_walk_ppo/policy_May14_08-35-32_8800.yaml"